export const ka = {
  common: {
    personTypes: {
      ADMIN: "ადმინისტრატორი",
      PLAYER: "მოთამაშე",
      STAFF: "პერსონალი",
    },
    appName: "აისის ჩემპიონატი",
    appFullName: "აისის ფეხბურთის ჩემპიონატი",
    season: "სეზონი {year}",
    or: "ან",
    vs: "VS",
    save: "შენახვა",
    saving: "ინახება...",
    cancel: "გაუქმება",
    edit: "რედაქტირება",
    delete: "წაშლა",
    close: "დახურვა",
    back: "უკან",
    viewAll: "ყველას ნახვა",
    loading: "იტვირთება...",
    noData: "მონაცემები არ არის",
    allRightsReserved: "ყველა უფლება დაცულია.",
    madeInGeorgia: "საქართველოში შექმნილი სიყვარულით",
    footballChampionship: "ფეხბურთის ჩემპიონატი",
    optional: "არასავალდებულო",
    website: "ვებსაიტი",
  },

  nav: {
    signIn: "შესვლა",
    signOut: "გასვლა",
    register: "რეგისტრაცია",
    users: "მომხმარებლები",
    messages: "შეტყობინებები",
  },

  chat: {
    title: "მიწერეთ ადმინისტრატორს",
    placeholder: "შეიყვანეთ შეტყობინება...",
    send: "გაგზავნა",
    sending: "იგზავნება...",
    noMessages: "შეტყობინებები არ არის.",
    yourMessage: "თქვენი შეტყობინება",
    adminReply: "პასუხი ადმინისტრატორისგან",
    reply: "პასუხი",
    replyPlaceholder: "შეიყვანეთ პასუხი...",
    replying: "იგზავნება...",
    sent: "გაგზავნილია",
  },

  landing: {
    title: "აისის საფეხბურთო",
    subtitle: "ჩემპიონატი",
    description: "გამარჯვება იწყება აქ!",
    viewChampionships: "ჩემპიონატების ნახვა",
    myDashboard: "ჩემი პანელი",
    joinAsPlayer: "შემოგვიერთდი",
    championships: "ჩემპიონატები",
    teams: "გუნდები",
    players: "მოთამაშეები",
    matches: "მატჩები",
    upcomingMatches: "მომავალი მატჩები",
  },

  auth: {
    loginTitle: "შეუერთდი შენს გუნდს",
    loginSubtitle: "შეიყვანე ტელეფონის ნომერი და პაროლი",
    loginHeroTitle: "აისის საფეხბურთო",
    loginHeroSubtitle: "ჩემპიონატი",
    loginHeroDesc: "გამარჯვება იწყება აქ!",
    registerTitle: "რეგისტრაციისთვის მზად ?",
    registerSubtitle: "შექმენი ან აირჩიე საჩემპიონო გუნდი",
    registerHeroTitle: "აისის საფეხბურთო",
    registerHeroSubtitle: "ჩემპიონატი",
    registerHeroDesc: "გამარჯვება იწყება აქ!",
    fullName: "სრული სახელი",
    fullNamePlaceholder: "მაგ. გიორგი მამარდაშვილი",
    email: "ელფოსტა",
    emailPlaceholder: "მაგ. name@example.com",
    phone: "ტელეფონის ნომერი",
    phonePlaceholder: "+995 555 123 456",
    phonePlaceholderFlexible: "+995 555 123 456",
    phoneInvalid: "შეიყვანე სწორი ქართული ნომერი (მაგ. +995 555 123 456)",
    password: "პაროლი",
    passwordPlaceholder: "შეიყვანე პაროლი",
    confirmPassword: "დაადასტურე პაროლი",
    confirmPlaceholder: "გაიმეორე",
    minChars: "მინ. 6 სიმბოლო",
    socialProfile: "სოციალური პროფილი",
    socialPlaceholder: "https://facebook.com/yourprofile",
    signingIn: "შესვლა...",
    signIn: "შესვლა",
    creatingAccount: "იქმნება...",
    createAccount: "ანგარიშის შექმნა",
    noAccount: "არ გაქვს ანგარიში?",
    hasAccount: "უკვე გაქვს ანგარიში?",
    passwordsMismatch: "პაროლები არ ემთხვევა",
  },

  championship: {
    title: "ჩემპიონატები",
    manageDesc: "მართე შენი ფეხბურთის ჩემპიონატები",
    browseDesc: "დაათვალიერე ფეხბურთის ჩემპიონატები",
    newChampionship: "ახალი ჩემპიონატი",
    noChampionships: "ჩემპიონატები ჯერ არ არის. შექმენი პირველი!",
    teams: "გუნდი",
    matches: "მატჩი",
    sponsors: "სპონსორი",
    maxPlayersPerTeam: "მაქს. {n} მოთამაშე გუნდში",
    createTitle: "ჩემპიონატის შექმნა",
    championshipName: "ჩემპიონატის სახელი",
    championshipNamePlaceholder: "მაგ. საგაზაფხულო ლიგა 2026",
    description: "აღწერა",
    descriptionPlaceholder: "ჩემპიონატის მოკლე აღწერა (არასავალდებულო)",
    maxTeams: "გუნდებების რაოდენობა",
    maxPlayersTeam: "სასტარტო მოთამაშეების რაოდენობა გუნდში",
    creating: "იქმნება...",
    backToChampionships: "← ჩემპიონატები",
    teamsAndPlayers: "გუნდი · {n} მოთამაშე თითოეულში",
    status: {
      DRAFT: "მონახაზი",
      REGISTRATION: "რეგისტრაცია",
      ACTIVE: "აქტიური",
      COMPLETED: "დასრულებული",
      CANCELLED: "გაუქმებული",
    },
    yourChampionship: "შენი ჩემპიონატი",
  },

  tabs: {
    teams: "გუნდები",
    players: "მოთამაშეები",
    matches: "მატჩები",
    staff: "პერსონალი",
    sponsors: "სპონსორები",
    prizes: "პრიზები",
    settings: "პარამეტრები",
  },

  nomination: {
    title: "ნომინაციები და პრიზები",
    subtitle: "ყველა ნომინაცია, პრიზი და სპონსორი",
    addNomination: "ნომინაციის დამატება",
    addNominationHint: "ქვემოთ დაუმატე ნომინაცია, შემდეგ კი შეგიძლია გამარჯვებულის მინიჭება.",
    noNominations: "ნომინაციები ჯერ არ არის.",
    name: "ნომინაცია",
    namePlaceholder: "მაგ. საუკეთესო მოთამაშე",
    prize: "პრიზი",
    prizePlaceholder: "მაგ. ოქროს ბურთი",
    sponsor: "სპონსორი",
    sponsorOptional: "სპონსორი (არასავალდებულო)",
    winner: "გამარჯვებული",
    noWinner: "ჯერ არ არის მინიჭებული",
    assignWinner: "გამარჯვებულის მინიჭება",
    selectWinner: "აირჩიე გამარჯვებული...",
    winnerTypePlayer: "მოთამაშე",
    winnerTypeStaff: "პერსონალი",
    winnerTypeTeam: "გუნდი",
    creating: "იქმნება...",
    create: "შექმნა",
    edit: "რედაქტირება",
    delete: "წაშლა",
    deleteConfirm: "წავშალოთ ნომინაცია?",
    saved: "შენახულია",
    selectSponsor: "აირჩიე სპონსორი...",
    noSponsor: "სპონსორი არ არის",
  },

  settings: {
    title: "ადმინის პარამეტრები",
    numberOfTeams: "გუნდების რაოდენობა",
    playersPerTeam: "მოთამაშეები გუნდში",
    maxReservesPerTeam: "სათადარიგო მოთამაშეების რაოდენობა",
    status: "სტატუსი",
    settingsUpdated: "პარამეტრები განახლდა",
    tournamentBracket: "ტურნირის ბადე",
    bracketDesc: "შეარჩიე გუნდები შემთხვევით და შექმენი ნოკაუტ ტურნირის ბადე.",
    bracketWillReplace: "ეს ჩაანაცვლებს არსებულ მატჩებს.",
    teamsRegistered: "გუნდი დარეგისტრირებულია",
    needAtLeast2: "(საჭიროა მინ. 2)",
    confirmRedraw: "ეს წაშლის ყველა არსებულ მატჩს და შექმნის ახალ ბადეს. გაგრძელება?",
    bracketGenerated: "ბადე შეიქმნა! {matches} მატჩი {rounds} რაუნდში.",
    failedGenerate: "ბადის გენერირება ვერ მოხერხდა",
    generating: "იქმნება...",
    redrawBracket: "თავიდან დახატვა",
    drawBracket: "ბადის დახატვა",
    deleteChampionship: "ჩემპიონატის წაშლა",
    confirmDeleteChampionship: "ნამდვილად წავშალოთ ჩემპიონატი? ყველა გუნდი, მატჩი და მონაცემი წაიშლება.",
    championshipDeleted: "ჩემპიონატი წაიშალა",
  },

  team: {
    title: "გუნდები",
    allTeamsDesc: "ყველა დარეგისტრირებული გუნდი",
    newTeam: "ახალი გუნდი",
    noTeams: "გუნდები ჯერ არ არის.",
    addTeam: "გუნდის დამატება",
    teamName: "გუნდის სახელი",
    teamNamePlaceholder: "მაგ. თბილისი FC",
    championship: "ჩემპიონატი",
    selectChampionship: "აირჩიე ჩემპიონატი",
    creating: "იქმნება...",
    createTeam: "გუნდის შექმნა",
    activePlayers: "აქტიური მოთამაშეები",
    reserve: "სათადარიგო",
    totalMembers: "სულ წევრები",
    captain: "კაპიტანი",
    player: "მოთამაშე",
    squadList: "შემადგენლობა ({n} / {max})",
    reserveBench: "სათადარიგო ({n} / {max})",
    noPlayersYet: "მოთამაშეები ჯერ არ არის. დააჭირე მოედანზე ცარიელ პოზიციებს მოთამაშეების დასამატებლად.",
    position: "პოზიცია",
    role: "როლი",
    joined: "შეუერთდა",
    editTeamName: "გუნდის სახელის რედაქტირება",
    playersLabel: "მოთამაშე",
    reservesLabel: "სათადარიგო",
    moveToReserve: "სათადარიგოში",
    moveToActive: "შემადგენლობაში",
    swapWithReserve: "შეცვალე სათადარიგოსთან",
    swapWithActive: "შეცვალე შემადგენლობასთან",
    selectPlayerToSwap: "აირჩიე მოთამაშე შესაცვლელად",
    join: "დაემატე",
    joinHint: "აირჩიე პოზიცია მოედანზე და შეუერთდი გუნდს. თუ შემადგენლობა სავსეა, შეუერთდი სათადარიგოდ.",
    allTeamsFullTitle: "ყველა გუნდი სავსეა",
    allTeamsFullMessage: "ამჟამად ყველა გუნდი სავსეა. თქვენ სათადარიგო სიაში ხართ. ადმინისტრატორი შეეცდება ადგილი მოგიძლიოთ და მალე დაგიკავშირდებათ.",
    removeConfirm: "წავშალოთ {name} გუნდიდან?",
    teamsCount: "გუნდები ({n} / {max})",
  },

  match: {
    title: "მატჩები",
    noMatches: "მატჩები ჯერ არ არის. გადადი პარამეტრებში ტურნირის ბადის შესაქმნელად.",
    tournamentBracket: "ტურნირის ბადე",
    enterResults: "შედეგების შეტანა",
    backToBracket: "← ბადესთან დაბრუნება",
    winner: "გამარჯვებული:",
    matchStaff: "მატჩის პერსონალი",
    matchInfo: "მატჩის ინფორმაცია",
    noMatchDetails: "მატჩის დეტალები ჯერ არ არის. დააჭირე რედაქტირებას თარიღის, დროის, ადგილის და აღწერის დასამატებლად.",
    viewOnMap: "რუკაზე ნახვა",
    editMatchInfo: "მატჩის ინფო რედაქტირება",
    date: "თარიღი",
    time: "დრო",
    location: "ადგილი",
    locationPlaceholder: "მაგ. ბორის პაიჭაძის სტადიონი, თბილისი",
    googleMapsUrl: "Google Maps ბმული",
    googleMapsPlaceholder: "https://maps.google.com/...",
    description: "აღწერა",
    descriptionPlaceholder: "მატჩის შენიშვნები, სპეციალური ინსტრუქციები...",
    failedToSave: "შენახვა ვერ მოხერხდა",
    saveMatchInfo: "მატჩის ინფოს შენახვა",
    noDrawAllowed: "ნოკაუტ მატჩებში ფრე დაუშვებელია. ქულები უნდა განსხვავდებოდეს.",
    tbd: "TBD",
    round: {
      final: "ფინალი",
      semiFinal: "ნახევარფინალი",
      quarterFinal: "მეოთხედფინალი",
      roundN: "რაუნდი {n}",
    },
    champion: "ჩემპიონი!",
    bye: "BYE",
    homeScore: "სახლის ქულა",
    awayScore: "სტუმრის ქულა",
    updateMatch: "მატჩის განახლება",
    scheduled: "დაგეგმილი",
    live: "მიმდინარე",
    completed: "დასრულებული",
    cancelled: "გაუქმებული",
    statusMap: {
      SCHEDULED: "დაგეგმილი",
      LIVE: "მიმდინარე",
      COMPLETED: "დასრულებული",
      CANCELLED: "გაუქმებული",
    } as Record<string, string>,
    schedule: "განრიგი",
    seeMatchesCalendar: "მატჩების კალენდრის ნახვა",
    noDatesYet: "თარიღები ჯერ არ არის. ადმინი დააყენებს მატჩების თარიღებს.",
    viewMatch: "მატჩის ნახვა",
    suggestedFromOtherMatch: "შემოთავაზებულია სხვა მატჩიდან. გააკეთე მცირე ცვლილებები და შეინახე.",
  },

  staff: {
    title: "პერსონალი",
    membersCount: "{n} პერსონალის წევრი დარეგისტრირებულია",
    addStaff: "პერსონალის დამატება",
    allStaff: "ყველა პერსონალი",
    noStaff: "პერსონალის წევრები ჯერ არ არის. დააჭირე \"პერსონალის დამატება\" ახლის შესაქმნელად.",
    name: "სახელი",
    staffRole: "როლი",
    phoneLabel: "ტელეფონი",
    assignments: "მინიჭებები",
    noAssignments: "მინიჭებები არ არის",
    more: "+{n} სხვა",
    addStaffMember: "პერსონალის წევრის დამატება",
    fullNamePlaceholder: "მაგ. გიორგი კვარაცხელია",
    phonePlaceholder: "+995555123456",
    selectRole: "აირჩიე როლი...",
    adding: "ემატება...",
    staffAssignments: "პერსონალის მინიჭებები ({n} წევრი)",
    addStaffUser: "პერსონალის დამატება",
    noStaffAssigned: "პერსონალი ჯერ არ არის მინიჭებული. მინიჭება მატჩის დეტალების გვერდიდან.",
    staffMember: "პერსონალის წევრი",
    type: "ტიპი",
    matchesAssigned: "მინიჭებული მატჩები",
    roles: "როლები",
    assignStaff: "პერსონალის მინიჭება",
    noStaffOnMatch: "ამ მატჩზე პერსონალი ჯერ არ არის მინიჭებული.",
    selectStaff: "აირჩიე...",
    matchRole: "მატჩის როლი",
    assigning: "ინიშნება...",
    assign: "მინიჭება",
    failedAssign: "პერსონალის მინიჭება ვერ მოხერხდა",
    failedRemove: "პერსონალის წაშლა ვერ მოხერხდა",
    allAssigned: "ყველა პერსონალი უკვე მინიჭებულია.",
    roles_list: {
      referee: "მსაჯი",
      assistantReferee: "მსაჯის ასისტენტი",
      doctor: "ექიმი",
      photographer: "ფოტოგრაფი",
      fourthOfficial: "მეოთხე მსაჯი",
    },
    staffRoleMap: {
      Referee: "მსაჯი",
      "Assistant Referee": "მსაჯის ასისტენტი",
      Doctor: "ექიმი",
      Photographer: "ფოტოგრაფი",
      "Fourth Official": "მეოთხე მსაჯი",
    } as Record<string, string>,
  },

  player: {
    profileTitle: "მოთამაშის პროფილი",
    statistics: "სტატისტიკა",
    matchesPlayed: "მატჩი",
    goals: "გოლი",
    assists: "პასი",
    history: "ისტორია",
    shareProfile: "ბმულის კოპირება",
    linkCopied: "კოპირებულია!",
    noHistory: "ჯერ არ არის გუნდებში",
    /** 4 პოზიციის კატეგორია */
    positionMap: {
      GK: "მეკარე",
      DEF: "დაცვა",
      MID: "ნახევარდაცვა",
      ATT: "შეტევა",
    } as Record<string, string>,
    /** დეტალური პოზიციიდან კატეგორიაზე გადაყვანა */
    positionToCategory: {
      GK: "GK",
      CB: "DEF",
      LB: "DEF",
      RB: "DEF",
      CDM: "MID",
      CM: "MID",
      CAM: "MID",
      LW: "ATT",
      RW: "ATT",
      ST: "ATT",
    } as Record<string, string>,
    activePlayers: "აქტიური მოთამაშეები ({n})",
    noActivePlayers: "აქტიური მოთამაშეები არ არის.",
    reservePlayers: "სათადარიგო მოთამაშეები ({n})",
    team: "გუნდი",
    position: "პოზიცია",
    role: "როლი",
    addReserve: "სათადარიგოში დამატება ({n}/{max})",
    addReserveTitle: "სათადარიგო მოთამაშის დამატება",
    joinAsReserve: "შეუერთდი ამ გუნდს სათადარიგოდ",
    joining: "უერთდება...",
    joinReserve: "სათადარიგოდ შესვლა",
    selectPlayer: "აირჩიე მოთამაშე...",
    noUnassigned: "თავისუფალი მოთამაშეები არ არის.",
    playersWithoutTeam: "მოთამაშეები გუნდის გარეშე ({n})",
    noPlayersWithoutTeam: "გუნდის გარეშე მოთამაშეები არ არის.",
    playersWithoutTeamDesc: "ყველა გუნდი და სათადარიგო სავსეა. ეს მოთამაშეები რეგისტრირებულები არიან, მაგრამ გუნდში ვერ შეუერთდნენ.",
    addAsReserve: "სათადარიგოდ დამატება",
    selectUnassigned: "აირჩიე თავისუფალი მოთამაშე სათადარიგოდ დასამატებლად",
  },

  pitch: {
    saving: "ინახება...",
    dragHint: "გადაათრიე მოთამაშეები მოედანზე",
    failedSave: "პოზიციის შენახვა ვერ მოხერხდა",
  },

  slot: {
    addPlayerTitle: "მოთამაშის დამატება — {position}",
    joinAsPosition: "შეუერთდი ამ გუნდს — {position}",
    joining: "უერთდება...",
    joinTeam: "გუნდში შესვლა",
    selectForPosition: "აირჩიე თავისუფალი მოთამაშე — {position}",
    choosePlayer: "აირჩიე მოთამაშე...",
    noUnassigned: "თავისუფალი მოთამაშეები არ არის.",
    adding: "ემატება...",
    addPlayer: "მოთამაშის დამატება",
  },

  sponsor: {
    title: "სპონსორები ({n})",
    noSponsors: "სპონსორები არ არის მინიჭებული.",
    assignExisting: "არსებული სპონსორის მინიჭება",
    selectSponsor: "აირჩიე სპონსორი...",
    assigning: "ინიშნება...",
    orCreateNew: "ან შექმენი ახალი სპონსორი",
    sponsorName: "სპონსორის სახელი",
    sponsorNamePlaceholder: "მაგ. თი-ბი-სი ბანკი",
    websitePlaceholder: "https://website.com",
    logoUrl: "ლოგოს ბმული",
    logoUrlPlaceholder: "https://example.com/logo.png",
    creatingAssigning: "იქმნება...",
    createAndAssign: "შექმნა და მინიჭება",
    addSponsor: "სპონსორის დამატება",
  },

  fixtures: {
    confirmReplace: "ეს ჩაანაცვლებს ყველა არსებულ მატჩს. გაგრძელება?",
    generated: "შეიქმნა {n} მატჩი {rounds} რაუნდში!",
    generating: "იქმნება...",
    generate: "მატჩების გენერირება",
  },

  dashboard: {
    title: "პანელი",
  },

  profile: {
    title: "პროფილი",
  },

  users: {
    title: "მომხმარებლები",
    subtitle: "ყველა რეგისტრირებული მომხმარებლის პირადი მონაცემები",
    allUsers: "ყველა მომხმარებელი",
    noUsers: "მომხმარებლები ჯერ არ არის.",
    searchPlaceholder: "ძებნა სახელით ან ტელეფონით...",
    search: "ძებნა",
    fullName: "სრული სახელი",
    email: "ელფოსტა",
    phone: "ტელეფონი",
    socialProfile: "სოციალური პროფილი",
    role: "როლი",
    position: "პოზიცია",
    registered: "დარეგისტრირდა",
  },
} as const;

export type Translations = typeof ka;

/** პოზიციის ქართული ლეიბლი (4 კატეგორია: მეკარე, დაცვა, ნახევარდაცვა, შეტევა) */
export function getPositionLabel(position: string | null | undefined): string {
  if (!position) return "—";
  const category = ka.player.positionToCategory[position] ?? position;
  return ka.player.positionMap[category] ?? position;
}
