export const ka = {
  common: {
    personTypes: {
      ADMIN: "ადმინისტრატორი",
      PLAYER: "მოთამაშე",
      STAFF: "პერსონალი",
    },
    appName: "აისის ჩემპიონატი",
    appFullName: "აისის ფეხბურთის ჩემპიონატი",
    season: "სეზონი 2026",
    or: "ან",
    vs: "VS",
    save: "შენახვა",
    saving: "ინახება...",
    cancel: "გაუქმება",
    edit: "რედაქტირება",
    delete: "წაშლა",
    close: "დახურვა",
    back: "უკან",
    viewAll: "ყველას ნახვა",
    loading: "იტვირთება...",
    noData: "მონაცემები არ არის",
    allRightsReserved: "ყველა უფლება დაცულია.",
    madeInGeorgia: "საქართველოში შექმნილი სიყვარულით",
    footballChampionship: "ფეხბურთის ჩემპიონატი",
    optional: "არასავალდებულო",
    website: "ვებსაიტი",
  },

  nav: {
    signIn: "შესვლა",
    signOut: "გასვლა",
    register: "რეგისტრაცია",
  },

  landing: {
    title: "აისის საფეხბურთო",
    subtitle: "ჩემპიონატი",
    description: "",
    viewChampionships: "ჩემპიონატების ნახვა",
    myDashboard: "ჩემი პანელი",
    joinAsPlayer: "შემოგვიერთდი",
    championships: "ჩემპიონატები",
    teams: "გუნდები",
    players: "მოთამაშეები",
    matches: "მატჩები",
    upcomingMatches: "მომავალი მატჩები",
  },

  auth: {
    loginTitle: "კეთილი იყოს შენი დაბრუნება",
    loginSubtitle: "შეიყვანე ტელეფონის ნომერი და პაროლი",
    loginHeroTitle: "AISI ფეხბურთის",
    loginHeroSubtitle: "ჩემპიონატი",
    loginHeroDesc: "ქართული ფეხბურთის გული. შემოუერთდი თამაშს, უხელმძღვანელე გუნდს, იბრძოლე გამარჯვებისთვის.",
    registerTitle: "ანგარიშის შექმნა",
    registerSubtitle: "დარეგისტრირდი ჩემპიონატში მონაწილეობისთვის",
    registerHeroTitle: "შემოუერთდი",
    registerHeroSubtitle: "ჩემპიონატს",
    registerHeroDesc: "დარეგისტრირდი მოთამაშედ, შეუერთდი გუნდს და იბრძოლე გამარჯვებისთვის ქართულ ფეხბურთის ასპარეზზე.",
    fullName: "სრული სახელი",
    fullNamePlaceholder: "მაგ. გიორგი მამარდაშვილი",
    phone: "ტელეფონის ნომერი",
    phonePlaceholder: "+995 555 123 456",
    password: "პაროლი",
    passwordPlaceholder: "შეიყვანე პაროლი",
    confirmPassword: "დაადასტურე პაროლი",
    confirmPlaceholder: "გაიმეორე",
    minChars: "მინ. 6 სიმბოლო",
    socialProfile: "სოციალური პროფილი",
    socialPlaceholder: "https://facebook.com/yourprofile",
    signingIn: "შესვლა...",
    signIn: "შესვლა",
    creatingAccount: "იქმნება...",
    createAccount: "ანგარიშის შექმნა",
    noAccount: "არ გაქვს ანგარიში?",
    hasAccount: "უკვე გაქვს ანგარიში?",
    passwordsMismatch: "პაროლები არ ემთხვევა",
  },

  championship: {
    title: "ჩემპიონატები",
    manageDesc: "მართე შენი ფეხბურთის ჩემპიონატები",
    browseDesc: "დაათვალიერე ფეხბურთის ჩემპიონატები",
    newChampionship: "ახალი ჩემპიონატი",
    noChampionships: "ჩემპიონატები ჯერ არ არის. შექმენი პირველი!",
    teams: "გუნდი",
    matches: "მატჩი",
    sponsors: "სპონსორი",
    maxPlayersPerTeam: "მაქს. {n} მოთამაშე გუნდში",
    createTitle: "ჩემპიონატის შექმნა",
    championshipName: "ჩემპიონატის სახელი",
    championshipNamePlaceholder: "მაგ. საგაზაფხულო ლიგა 2026",
    maxTeams: "მაქსიმუმ გუნდები",
    maxPlayersTeam: "მოთამაშეები / გუნდი",
    creating: "იქმნება...",
    backToChampionships: "← ჩემპიონატები",
    teamsAndPlayers: "გუნდი · {n} მოთამაშე თითოეულში",
    status: {
      DRAFT: "მონახაზი",
      REGISTRATION: "რეგისტრაცია",
      ACTIVE: "აქტიური",
      COMPLETED: "დასრულებული",
      CANCELLED: "გაუქმებული",
    },
  },

  tabs: {
    teams: "გუნდები",
    players: "მოთამაშეები",
    matches: "მატჩები",
    staff: "პერსონალი",
    sponsors: "სპონსორები",
    settings: "პარამეტრები",
  },

  settings: {
    title: "ადმინის პარამეტრები",
    numberOfTeams: "გუნდების რაოდენობა",
    playersPerTeam: "მოთამაშეები გუნდში",
    maxReservesPerTeam: "მაქს. სათადარიგო",
    status: "სტატუსი",
    settingsUpdated: "პარამეტრები განახლდა",
    tournamentBracket: "ტურნირის ბადე",
    bracketDesc: "შეარჩიე გუნდები შემთხვევით და შექმენი ნოკაუტ ტურნირის ბადე.",
    bracketWillReplace: "ეს ჩაანაცვლებს არსებულ მატჩებს.",
    teamsRegistered: "გუნდი დარეგისტრირებულია",
    needAtLeast2: "(საჭიროა მინ. 2)",
    confirmRedraw: "ეს წაშლის ყველა არსებულ მატჩს და შექმნის ახალ ბადეს. გაგრძელება?",
    bracketGenerated: "ბადე შეიქმნა! {matches} მატჩი {rounds} რაუნდში.",
    failedGenerate: "ბადის გენერირება ვერ მოხერხდა",
    generating: "იქმნება...",
    redrawBracket: "თავიდან დახატვა",
    drawBracket: "ბადის დახატვა",
  },

  team: {
    title: "გუნდები",
    allTeamsDesc: "ყველა დარეგისტრირებული გუნდი",
    newTeam: "ახალი გუნდი",
    noTeams: "გუნდები ჯერ არ არის.",
    addTeam: "გუნდის დამატება",
    teamName: "გუნდის სახელი",
    teamNamePlaceholder: "მაგ. თბილისი FC",
    championship: "ჩემპიონატი",
    selectChampionship: "აირჩიე ჩემპიონატი",
    creating: "იქმნება...",
    createTeam: "გუნდის შექმნა",
    activePlayers: "აქტიური მოთამაშეები",
    reserve: "სათადარიგო",
    totalMembers: "სულ წევრები",
    captain: "კაპიტანი",
    player: "მოთამაშე",
    squadList: "შემადგენლობა ({n} / {max})",
    reserveBench: "სათადარიგო ({n} / {max})",
    noPlayersYet: "მოთამაშეები ჯერ არ არის. დააჭირე მოედანზე ცარიელ პოზიციებს მოთამაშეების დასამატებლად.",
    position: "პოზიცია",
    role: "როლი",
    joined: "შეუერთდა",
    editTeamName: "გუნდის სახელის რედაქტირება",
    playersLabel: "მოთამაშე",
    reservesLabel: "სათადარიგო",
    removeConfirm: "წავშალოთ {name} გუნდიდან?",
    teamsCount: "გუნდები ({n} / {max})",
  },

  match: {
    title: "მატჩები",
    noMatches: "მატჩები ჯერ არ არის. გადადი პარამეტრებში ტურნირის ბადის შესაქმნელად.",
    tournamentBracket: "ტურნირის ბადე",
    enterResults: "შედეგების შეტანა",
    backToBracket: "← ბადესთან დაბრუნება",
    winner: "გამარჯვებული:",
    matchStaff: "მატჩის პერსონალი",
    matchInfo: "მატჩის ინფორმაცია",
    noMatchDetails: "მატჩის დეტალები ჯერ არ არის. დააჭირე რედაქტირებას თარიღის, დროის, ადგილის და აღწერის დასამატებლად.",
    viewOnMap: "რუკაზე ნახვა",
    editMatchInfo: "მატჩის ინფო რედაქტირება",
    date: "თარიღი",
    time: "დრო",
    location: "ადგილი",
    locationPlaceholder: "მაგ. ბორის პაიჭაძის სტადიონი, თბილისი",
    googleMapsUrl: "Google Maps ბმული",
    googleMapsPlaceholder: "https://maps.google.com/...",
    description: "აღწერა",
    descriptionPlaceholder: "მატჩის შენიშვნები, სპეციალური ინსტრუქციები...",
    failedToSave: "შენახვა ვერ მოხერხდა",
    saveMatchInfo: "მატჩის ინფოს შენახვა",
    noDrawAllowed: "ნოკაუტ მატჩებში ფრე დაუშვებელია. ქულები უნდა განსხვავდებოდეს.",
    tbd: "TBD",
    round: {
      final: "ფინალი",
      semiFinal: "ნახევარფინალი",
      quarterFinal: "მეოთხედფინალი",
      roundN: "რაუნდი {n}",
    },
    champion: "ჩემპიონი!",
    bye: "BYE",
    homeScore: "სახლის ქულა",
    awayScore: "სტუმრის ქულა",
    updateMatch: "მატჩის განახლება",
    scheduled: "დაგეგმილი",
    live: "მიმდინარე",
    completed: "დასრულებული",
    cancelled: "გაუქმებული",
    statusMap: {
      SCHEDULED: "დაგეგმილი",
      LIVE: "მიმდინარე",
      COMPLETED: "დასრულებული",
      CANCELLED: "გაუქმებული",
    } as Record<string, string>,
  },

  staff: {
    title: "პერსონალი",
    membersCount: "{n} პერსონალის წევრი დარეგისტრირებულია",
    addStaff: "პერსონალის დამატება",
    allStaff: "ყველა პერსონალი",
    noStaff: "პერსონალის წევრები ჯერ არ არის. დააჭირე \"პერსონალის დამატება\" ახლის შესაქმნელად.",
    name: "სახელი",
    staffRole: "როლი",
    phoneLabel: "ტელეფონი",
    assignments: "მინიჭებები",
    noAssignments: "მინიჭებები არ არის",
    more: "+{n} სხვა",
    addStaffMember: "პერსონალის წევრის დამატება",
    fullNamePlaceholder: "მაგ. გიორგი კვარაცხელია",
    phonePlaceholder: "+995555123456",
    selectRole: "აირჩიე როლი...",
    adding: "ემატება...",
    staffAssignments: "პერსონალის მინიჭებები ({n} წევრი)",
    addStaffUser: "პერსონალის დამატება",
    noStaffAssigned: "პერსონალი ჯერ არ არის მინიჭებული. მინიჭება მატჩის დეტალების გვერდიდან.",
    staffMember: "პერსონალის წევრი",
    type: "ტიპი",
    matchesAssigned: "მინიჭებული მატჩები",
    roles: "როლები",
    assignStaff: "პერსონალის მინიჭება",
    noStaffOnMatch: "ამ მატჩზე პერსონალი ჯერ არ არის მინიჭებული.",
    selectStaff: "აირჩიე...",
    matchRole: "მატჩის როლი",
    assigning: "ინიშნება...",
    assign: "მინიჭება",
    failedAssign: "პერსონალის მინიჭება ვერ მოხერხდა",
    failedRemove: "პერსონალის წაშლა ვერ მოხერხდა",
    allAssigned: "ყველა პერსონალი უკვე მინიჭებულია.",
    roles_list: {
      referee: "მსაჯი",
      assistantReferee: "მსაჯის ასისტენტი",
      doctor: "ექიმი",
      photographer: "ფოტოგრაფი",
      fourthOfficial: "მეოთხე მსაჯი",
    },
    staffRoleMap: {
      Referee: "მსაჯი",
      "Assistant Referee": "მსაჯის ასისტენტი",
      Doctor: "ექიმი",
      Photographer: "ფოტოგრაფი",
      "Fourth Official": "მეოთხე მსაჯი",
    } as Record<string, string>,
  },

  player: {
    /** 4 პოზიციის კატეგორია */
    positionMap: {
      GK: "მეკარე",
      DEF: "დაცვა",
      MID: "ნახევარდაცვა",
      ATT: "შეტევა",
    } as Record<string, string>,
    /** დეტალური პოზიციიდან კატეგორიაზე გადაყვანა */
    positionToCategory: {
      GK: "GK",
      CB: "DEF",
      LB: "DEF",
      RB: "DEF",
      CDM: "MID",
      CM: "MID",
      CAM: "MID",
      LW: "ATT",
      RW: "ATT",
      ST: "ATT",
    } as Record<string, string>,
    activePlayers: "აქტიური მოთამაშეები ({n})",
    noActivePlayers: "აქტიური მოთამაშეები არ არის.",
    reservePlayers: "სათადარიგო მოთამაშეები ({n})",
    team: "გუნდი",
    position: "პოზიცია",
    role: "როლი",
    addReserve: "სათადარიგოს დამატება ({n}/{max})",
    addReserveTitle: "სათადარიგო მოთამაშის დამატება",
    joinAsReserve: "შეუერთდი ამ გუნდს სათადარიგოდ",
    joining: "უერთდება...",
    joinReserve: "სათადარიგოდ შესვლა",
    selectPlayer: "აირჩიე მოთამაშე...",
    noUnassigned: "თავისუფალი მოთამაშეები არ არის.",
    addAsReserve: "სათადარიგოდ დამატება",
    selectUnassigned: "აირჩიე თავისუფალი მოთამაშე სათადარიგოდ დასამატებლად",
  },

  pitch: {
    saving: "ინახება...",
    dragHint: "გადაათრიე მოთამაშეები მოედანზე",
    failedSave: "პოზიციის შენახვა ვერ მოხერხდა",
  },

  slot: {
    addPlayerTitle: "მოთამაშის დამატება — {position}",
    joinAsPosition: "შეუერთდი ამ გუნდს — {position}",
    joining: "უერთდება...",
    joinTeam: "გუნდში შესვლა",
    selectForPosition: "აირჩიე თავისუფალი მოთამაშე — {position}",
    choosePlayer: "აირჩიე მოთამაშე...",
    noUnassigned: "თავისუფალი მოთამაშეები არ არის.",
    adding: "ემატება...",
    addPlayer: "მოთამაშის დამატება",
  },

  sponsor: {
    title: "სპონსორები ({n})",
    noSponsors: "სპონსორები არ არის მინიჭებული.",
    assignExisting: "არსებული სპონსორის მინიჭება",
    selectSponsor: "აირჩიე სპონსორი...",
    assigning: "ინიშნება...",
    orCreateNew: "ან შექმენი ახალი სპონსორი",
    sponsorName: "სპონსორის სახელი",
    sponsorNamePlaceholder: "მაგ. თი-ბი-სი ბანკი",
    websitePlaceholder: "https://website.com",
    logoUrl: "ლოგოს ბმული",
    logoUrlPlaceholder: "https://example.com/logo.png",
    creatingAssigning: "იქმნება...",
    createAndAssign: "შექმნა და მინიჭება",
    addSponsor: "სპონსორის დამატება",
  },

  fixtures: {
    confirmReplace: "ეს ჩაანაცვლებს ყველა არსებულ მატჩს. გაგრძელება?",
    generated: "შეიქმნა {n} მატჩი {rounds} რაუნდში!",
    generating: "იქმნება...",
    generate: "მატჩების გენერირება",
  },

  dashboard: {
    title: "პანელი",
  },

  profile: {
    title: "პროფილი",
  },
} as const;

export type Translations = typeof ka;

/** პოზიციის ქართული ლეიბლი (4 კატეგორია: მეკარე, დაცვა, ნახევარდაცვა, შეტევა) */
export function getPositionLabel(position: string | null | undefined): string {
  if (!position) return "—";
  const category = ka.player.positionToCategory[position] ?? position;
  return ka.player.positionMap[category] ?? position;
}
